name: firebase_analytics_module
description: "help to use firebase_analytics in june_flow framework"
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/firebase_analytics_module

version: 1.0.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  firebase_analytics:  #@add
  firebase_core:
  flutter:
    sdk: flutter
  go_router:
  june_flow_util:

dev_dependencies:
  firebase_core_module: #@add
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/module/firebase_analytics_module/
  uses-material-design: true